analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Style rules
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    directives_ordering: true
    prefer_single_quotes: true
    unawaited_futures: true

    # Error prevention rules
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_type_to_string: true
    avoid_void_async: true
    empty_catches: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_null_checks: true
    unnecessary_statements: true

    # MVVM specific rules
    avoid_classes_with_only_static_members: false # Allow utility classes
    one_member_abstracts: false # Allow single-method interfaces for ViewModels

    # Documentation rules
    package_api_docs: true
    public_member_api_docs: false # Optional, enable if you want enforced documentation

    # Design rules
    avoid_unused_constructor_parameters: true
    prefer_constructors_over_static_methods: true
    prefer_final_fields: true
    sized_box_for_whitespace: true
    use_decorated_box: true
    use_key_in_widget_constructors: true

    # Async rules
    await_only_futures: true

    # File structure rules
    camel_case_types: true
    file_names: true
    library_private_types_in_public_api: true

    # Null safety rules
    avoid_returning_null_for_future: true
    null_check_on_nullable_type_parameter: true
    unnecessary_null_aware_assignments: true
    unnecessary_nullable_for_final_variable_declarations: true
