name: superkit_core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_cupertino_localizations: 1.0.1
  window_manager: ^0.3.7
  responsive_builder: ^0.7.0

  # Themes
  flex_color_scheme: ^7.3.1
  adaptive_theme: ^3.4.1

  # Icons & Fonts
  google_fonts: ^6.1.0
  flutter_iconly: ^1.0.2
  font_awesome_flutter: ^10.6.0
  flutter_svg: ">=1.0.0 <2.0.9"
  flutter_feather_icons: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  modal_side_sheet: ^0.0.1

  # Animations
  flutter_scale_tap: ^1.0.5
  auto_animated: ^3.0.1
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2
  animations: ">=2.0.0 <3.0.0"

  # Tools & Others
  go_router: ^12.0.1
  location: ^5.0.3
  collection: ">=1.15.0 <2.0.0"
  intersperse: ">=2.0.0 <3.0.0"
  url_launcher: ^6.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  package_info_plus: ^4.2.0
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  flutter_hooks: ^0.20.3
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    # Fonts
    - assets/google_fonts/poppins/
    - assets/google_fonts/plexsans/

    # Images
    - packages/superkit_core/assets/images/superkit_core.png
    - packages/superkit_core/assets/images/avatar.png
    - packages/superkit_core/assets/images/light.png
    - packages/superkit_core/assets/images/dark.png
    - packages/superkit_core/assets/images/system.png
