name: superkit_core
description: A new Flutter package project.
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_cupertino_localizations: 1.0.1
  window_manager: ^0.4.3
  responsive_builder: ^0.7.1

  # Themes
  flex_color_scheme: ^7.3.1
  adaptive_theme: ^3.6.0

  # Icons & Fonts
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  flutter_iconly: ^1.0.2

  # Animations
  flutter_scale_tap: ^1.0.5
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  animations: ">=2.0.0 <3.0.0"

  # Tools & Others
  cached_network_image: ^3.4.1
  percent_indicator:
    git: https://github.com/devllopa/flutter_percent_indicator.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    # Fonts
    - assets/google_fonts/poppins/
    - assets/google_fonts/plexsans/

    # Images
    - packages/superkit_core/assets/images/superkit_core.png
    - packages/superkit_core/assets/images/avatar.png
    - packages/superkit_core/assets/images/light.png
    - packages/superkit_core/assets/images/dark.png
    - packages/superkit_core/assets/images/system.png
