name: superkit_core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_cupertino_localizations: 1.0.1
  window_manager: ^0.3.8
  responsive_builder: ^0.7.0

  # Themes
  flex_color_scheme: ^7.3.1
  adaptive_theme: ^3.6.0

  # Icons & Fonts
  google_fonts: ^6.1.0
  flutter_iconly: ^1.0.2
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  flutter_feather_icons: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  modal_side_sheet: ^0.0.1

  # Animations
  flutter_scale_tap: ^1.0.5
  auto_animated: ^3.2.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  animations: '>=2.0.0 <3.0.0'

  # Tools & Others
  provider: ^6.0.5
  cached_network_image: ^3.3.1
  flutter_hooks: ^0.20.4
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    # Fonts
    - assets/google_fonts/poppins/
    - assets/google_fonts/plexsans/

    # Images
    - packages/superkit_core/assets/images/superkit_core.png
    - packages/superkit_core/assets/images/avatar.png
    - packages/superkit_core/assets/images/light.png
    - packages/superkit_core/assets/images/dark.png
    - packages/superkit_core/assets/images/system.png
